#yaml配置文件支持多profile, 可根据不同profile配置参数
spring.profiles.active: cmcc

logging:
  level: #日志级别, 可针对不同package设置
    root: info
    com.sky: info
param:
  appName: wildsky-population-od
  cityCode: 1000512
  districtCode: 1000512