#yaml配置文件支持多profile, 可根据不同profile配置参数
spring.profiles.active: cmcc

logging:
  level: #日志级别, 可针对不同package设置
    root: info
    com.sky: info
  #file: mobile.log

param:
  appName: wildsky-stat-process

---

#本机环境
spring.profiles: local

param:
  masterUrl: local[2]
  statpatitions: 1
  savePath: file:///Users/chenhu/data/yancheng/save/
  workLiveFile: file:///Users/chenhu/data/yancheng/save/work_live_his
  statBatchSize: 3
  validSignalFilesForStat:
    - /Users/chenhu/data/yancheng/save/validSignal/20170108
    - /Users/chenhu/data/yancheng/save/validSignal/20170109
    - /Users/chenhu/data/yancheng/save/validSignal/20170110
    - /Users/chenhu/data/yancheng/save/validSignal/20170111
    - /Users/chenhu/data/yancheng/save/validSignal/20170112
    - /Users/chenhu/data/yancheng/save/validSignal/20170113
    - /Users/chenhu/data/yancheng/save/validSignal/20170114
    - /Users/chenhu/data/yancheng/save/validSignal/20170115
    - /Users/chenhu/data/yancheng/save/validSignal/20170116
  odFiles:
    - /Users/chenhu/data/yancheng/save/od/20170108
    - /Users/chenhu/data/yancheng/save/od/20170109
    - /Users/chenhu/data/yancheng/save/od/20170110
    - /Users/chenhu/data/yancheng/save/od/20170111
    - /Users/chenhu/data/yancheng/save/od/20170112
    - /Users/chenhu/data/yancheng/save/od/20170113
    - /Users/chenhu/data/yancheng/save/od/20170114
    - /Users/chenhu/data/yancheng/save/od/20170115
    - /Users/chenhu/data/yancheng/save/od/20170116
  odTraceFiles:
    - /Users/chenhu/data/yancheng/save/od_trace/20170108
    - /Users/chenhu/data/yancheng/save/od_trace/20170109
    - /Users/chenhu/data/yancheng/save/od_trace/20170110
    - /Users/chenhu/data/yancheng/save/od_trace/20170111
    - /Users/chenhu/data/yancheng/save/od_trace/20170112
    - /Users/chenhu/data/yancheng/save/od_trace/20170113
    - /Users/chenhu/data/yancheng/save/od_trace/20170114
    - /Users/chenhu/data/yancheng/save/od_trace/20170115
    - /Users/chenhu/data/yancheng/save/od_trace/20170116
  odTripStatFiles:
    - /Users/chenhu/data/yancheng/save/stat_trip/20170108
    - /Users/chenhu/data/yancheng/save/stat_trip/20170109
    - /Users/chenhu/data/yancheng/save/stat_trip/20170110
    - /Users/chenhu/data/yancheng/save/stat_trip/20170111
    - /Users/chenhu/data/yancheng/save/stat_trip/20170112
    - /Users/chenhu/data/yancheng/save/stat_trip/20170113
    - /Users/chenhu/data/yancheng/save/stat_trip/20170114
    - /Users/chenhu/data/yancheng/save/stat_trip/20170115
    - /Users/chenhu/data/yancheng/save/stat_trip/20170116


---

#移动环境
spring.profiles: cmcc

param:
  statpatitions: 1
  statBatchSize: 7
  savePath: /user/bdoc/17/services/hdfs/132/nanjing/save/
  workLiveFile: /user/bdoc/17/services/hdfs/132/nanjing/save/work_live_his
  validSignalFilesForStat:
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191101
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191102
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191103
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191104
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191105
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191106
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191107
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191108
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191109
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191110
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191111
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191112
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191113
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191114
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191115
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191116
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191117
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191118
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191119
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191120
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191121
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191122
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191123
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191124
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191125
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191126
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191127
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191128
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191129
    - /user/bdoc/17/services/hdfs/132/nanjing/save/validSignal/20191130
  odFiles:
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191101
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191102
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191103
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191104
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191105
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191106
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191107
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191108
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191109
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191110
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191111
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191112
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191113
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191114
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191115
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191116
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191117
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191118
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191119
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191120
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191121
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191122
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191123
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191124
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191125
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191126
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191127
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191128
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191129
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od/20191130
  odTripStatFiles:
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191101
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191102
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191103
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191104
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191105
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191106
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191107
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191108
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191109
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191110
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191111
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191112
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191113
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191114
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191115
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191116
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191117
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191118
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191119
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191120
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191121
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191122
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191123
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191124
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191125
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191126
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191127
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191128
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191129
    - /user/bdoc/17/services/hdfs/132/nanjing/save/stat_trip/20191130
  odTraceFiles:
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od_trace/20191103
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od_trace/20191113
    - /user/bdoc/17/services/hdfs/132/nanjing/save/od_trace/20191123





