#yaml配置文件支持多profile, 可根据不同profile配置参数
spring.profiles.active: 201910

logging:
  level: #日志级别, 可针对不同package设置
    root: info
    com.sky: info
  #file: mobile.log
param:
  appName: wildsky-stat-process
  savePath: /user/bdoc/17/services/hdfs/132/changshu/save/