# 针对常熟需求中，需要对201910的数据分成两份进行 统计表1-1 人口分布集合数据表(Work-live-stat.zip)
# 本份统计是用2019年10月8-10月31日的数据计算出来的职住分析结果
param:
  workLiveFile: /user/bdoc/17/services/hdfs/132/changshu/save/201910-2/work_live_his
  validSignalFilesForStat:
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20191010
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20191015
  odFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20191010
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20191015
  odTripStatFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20191010
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20191015
  odTraceFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20191010
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20191015





