param:
  workLiveFile: /user/bdoc/17/services/hdfs/132/changshu/save/201706/work_live_his
  validSignalFilesForStat:
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20170612
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20170614
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20170616
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20170618
  odFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20170612
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20170614
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20170616
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20170618
  odTripStatFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20170612
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20170614
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20170616
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20170618
  odTraceFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20170612
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20170614
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20170616
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20170618





