# 针对常熟需求中，需要对201910的数据分成两份进行 统计表1-1 人口分布集合数据表(Work-live-stat.zip)
# 本份统计是用2019年10月1-10月7日的数据计算出来的职住分析结果
#---------------------详细说明----------------------------------------------
# 先分成两分做职住分析，第一份是2019年10月1-10月7日7天数据，第二份数据是2019年10月8-10月31日24天数据，
# 10月1号到7号里面出现的人所在第二份数据中出现则live_base和work_base 取第二份中数据，
# 若在第二份数据中没出现则认为此人是访客人口。与第一份统计出来的结果没关系,
# 没判断出来就按照第二份的结果统计,在第二份结果中判定为什么就是什么
param:
  workLiveFile: /user/bdoc/17/services/hdfs/132/changshu/save/201910-1/work_live_his
  workLiveFile2: /user/bdoc/17/services/hdfs/132/changshu/save/201910-2/work_live_his
  validSignalFilesForStat:
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20191001
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20191003
    - /user/bdoc/17/services/hdfs/132/changshu/save/validSignal/20191007
  odFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20191001
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20191003
    - /user/bdoc/17/services/hdfs/132/changshu/save/od/20191007
  odTripStatFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20191001
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20191003
    - /user/bdoc/17/services/hdfs/132/changshu/save/stat_trip/20191007
  odTraceFiles:
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20191001
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20191003
    - /user/bdoc/17/services/hdfs/132/changshu/save/od_trace/20191007