#yaml配置文件支持多profile, 可根据不同profile配置参数
spring.profiles.active: cmcc

logging:
  level: #日志级别, 可针对不同package设置
    root: info
    com.sky: info
  #file: mobile.log

param:
  appName: huaian-stat-process

---

#本机环境
spring.profiles: local

param:
  masterUrl: local[2]
  statpatitions: 1
  savePath: file:///Users/chenhu/data/yancheng/save/
  workLiveFile: file:///Users/chenhu/data/yancheng/save/work_live_his
  validSignalFilesForStat:
    - /Users/chenhu/data/yancheng/save/validSignal/20170108
    - /Users/chenhu/data/yancheng/save/validSignal/20170109
    - /Users/chenhu/data/yancheng/save/validSignal/20170110
    - /Users/chenhu/data/yancheng/save/validSignal/20170111
    - /Users/chenhu/data/yancheng/save/validSignal/20170112
    - /Users/chenhu/data/yancheng/save/validSignal/20170113
    - /Users/chenhu/data/yancheng/save/validSignal/20170114
    - /Users/chenhu/data/yancheng/save/validSignal/20170115
    - /Users/chenhu/data/yancheng/save/validSignal/20170116
  odFiles:
    - /Users/chenhu/data/yancheng/save/od/20170108
    - /Users/chenhu/data/yancheng/save/od/20170109
    - /Users/chenhu/data/yancheng/save/od/20170110
    - /Users/chenhu/data/yancheng/save/od/20170111
    - /Users/chenhu/data/yancheng/save/od/20170112
    - /Users/chenhu/data/yancheng/save/od/20170113
    - /Users/chenhu/data/yancheng/save/od/20170114
    - /Users/chenhu/data/yancheng/save/od/20170115
    - /Users/chenhu/data/yancheng/save/od/20170116
  odTraceFiles:
    - /Users/chenhu/data/yancheng/save/od_trace/20170108
    - /Users/chenhu/data/yancheng/save/od_trace/20170109
    - /Users/chenhu/data/yancheng/save/od_trace/20170110
    - /Users/chenhu/data/yancheng/save/od_trace/20170111
    - /Users/chenhu/data/yancheng/save/od_trace/20170112
    - /Users/chenhu/data/yancheng/save/od_trace/20170113
    - /Users/chenhu/data/yancheng/save/od_trace/20170114
    - /Users/chenhu/data/yancheng/save/od_trace/20170115
    - /Users/chenhu/data/yancheng/save/od_trace/20170116

---

#移动环境
spring.profiles: cmcc

param:
  statpatitions: 1
  savePath: /user/bdoc/17/services/hdfs/132/huaian/save/
  workLiveFile: /user/bdoc/17/services/hdfs/132/huaian/save/work_live_his
  validSignalFilesForStat:
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181015
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181016
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181017
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181018
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181019
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181020
    - /user/bdoc/17/services/hdfs/132/huaian/save/validSignal/20181021
  odFiles:
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181015
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181016
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181017
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181018
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181019
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181020
    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181021
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181022
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181023
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181024
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181025
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181026
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181027
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181028
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181029
#    - /user/bdoc/17/services/hdfs/132/huaian/save/od/20181031
  odTraceFiles:
    - /user/bdoc/17/services/hdfs/132/huaian/save/od_trace/20181003
    - /user/bdoc/17/services/hdfs/132/huaian/save/od_trace/20181013
    - /user/bdoc/17/services/hdfs/132/huaian/save/od_trace/20181023





