#yaml配置文件支持多profile, 可根据不同profile配置参数
spring.profiles.active: 201910-2

logging:
  level: #日志级别, 可针对不同package设置
    root: info
    com.sky: info
  #file: mobile.log

param:
  appName: wildsky-pre-process
  cityCode: 1000512
#  savePath: /user/bdoc/17/services/hdfs/132/changshu/save/
#  cellFile: /user/bdoc/17/services/hdfs/132/changshu/cell.csv
#  basePath: /user/bdoc/17/services/hdfs/132/changshu/tmp_changshu_track/
#  trackPre: dt=
#  phoneCityFile: /user/bdoc/17/services/hdfs/132/changshu/GSDZ.csv
#  baseFile: /user/bdoc/17/services/hdfs/132/changshu/save/baseArea.csv
#  userFile: /user/bdoc/17/services/hdfs/132/changshu/crm_new/
#  workliveBatchSize: 7